# [Ερώτημα 1: Πράξεις με Διανύσματα και Πίνακες]

Αρχικά δημιουργούμε:

i) Δύο τυχαίους πίνακες ακέραιων αριθμών $X \in ℤ^{3x4}, Y \in ℤ^{4x3}$ και

ii) Δύο τυχαία διανύσματα ακέραιων αριθμών $a \in ℤ^{4}, b \in ℤ^{4}$


In [ ]:
import numpy as np
np.random.seed(14)                    # seed = final 4 digits of AM
X = np.random.randint(0,10, (3,4))    # random numpy array of shape (3,4)
Y = np.random.randint(0,10, (4,3))    # random numpy array of shape (4,3)

a = np.random.randint(0,10,4)         #vector row (random numpy array of shape row)
b = np.random.randint(0,10,4)

print ("X:")
print(X)
print ("Y:")
print(Y)
print ("a:", end=" ")
print(a)
print ("b:", end=" ")
print(b)

X:
[[8 6 7 9]
 [6 0 8 9]
 [7 6 0 7]]
Y:
[[4 0 6]
 [4 5 5]
 [8 5 9]
 [8 7 3]]
a: [4 8 1 6]
b: [0 9 5 6]


#(1.1)
Το εσωτερικό γινόμενο των a=(4,8,1,6), b=(0,9,5,6) θα είναι:

$a^Tb = 
 \begin{pmatrix}
 4\\8\\1\\6
 \end{pmatrix}\begin{pmatrix}0,9,5,6\end{pmatrix}
 = 4 * 0 + 8 * 9 + 1 * 5 + 6 * 6 = 0 + 72 + 5 + 36 = 113 \\ $

#(1.2)
Το γινόμενο πίνακα-διανύσματος των $Xa \in Z^3$ θα είναι:

$Xa = 
 \begin{pmatrix}
  8 & 6 & 7 & 9 \\
  6 & 0 & 8 & 9 \\
  7  & 6  & 0 & 7
 \end{pmatrix}\begin{pmatrix}4,8,1,6\end{pmatrix}=
\begin{pmatrix}8\cdot4+6\cdot8+7\cdot1+9\cdot6,\quad6\cdot4+0\cdot8+8\cdot1+9\cdot6,\quad7\cdot4+6\cdot8+0\cdot1+7\cdot6\end{pmatrix}=(141,86,118) \\ $

#(1.3)
Το γινόμενο των πινάκων $XY \in Z^{3x3}$ θα είναι:

$XY = 
 \begin{pmatrix}
  8 & 6 & 7 & 9 \\
  6 & 0 & 8 & 9 \\
  7  & 6  & 0 & 7
 \end{pmatrix}
 \begin{pmatrix}
  4 & 0 & 6 \\
  4 & 5 & 5 \\
  8 & 5 & 9 \\
  8 & 7 & 3
 \end{pmatrix}= 
 \begin{pmatrix}
  8\cdot4+6\cdot4+7\cdot8+9\cdot8 & 8\cdot0+6\cdot5+7\cdot5+9\cdot7 & 8\cdot6+6\cdot5+7\cdot9+9\cdot3 \\
  6\cdot4+0\cdot4+8\cdot8+9\cdot8 & 6\cdot0+0\cdot5+8\cdot5+9\cdot7 & 6\cdot6+0\cdot5+8\cdot9+9\cdot3 \\
  7\cdot4+6\cdot4+0\cdot8+7\cdot8 & 7\cdot0+6\cdot5+0\cdot5+7\cdot7 & 7\cdot6+6\cdot5+0\cdot9+7\cdot3
 \end{pmatrix}=
 \begin{pmatrix}
  184 & 128 & 168 \\
  160 & 103 & 135 \\
  108 & 79 & 93
 \end{pmatrix}
\\ $


#(1.4)
Η Ευκλείδεια νόρμα (l2-norm) του διανύσματος a θα είναι:

$||a||_2 = \sqrt{a_1^2 + a_2^2 + a_3^2 + a_4^2} = \sqrt{4^2 + 8^2 + 1^2 + 6^2} = \sqrt{16 + 64 + 1 + 36} = \sqrt{117} = 10.8166538 \\ $

#(1.5)
Η  Frobenius νόρμα του πίνακα X θα είναι:

$||X||_F = \sqrt{X_{11}^2 + X_{21}^2 + X_{31}^2 + X_{12}^2 + X_{22}^2 + X_{32}^2 + X_{13}^2 + X_{23}^2 + X_{33}^2 + X_{14}^2 + X_{24}^2 + X_{34}^2} = 
\sqrt{8^2 + 6^2 + 7^2 + 6^2 + 0^2 + 6^2 + 7^2 + 8^2 + 0^2 + 9^2 + 9^2 + 7^2} = 
\sqrt{64 + 36 + 49 + 36 + 36 + 49 + 64 + 81 + 81 + 49} = \sqrt{545} = 23.3452351$
 

# Επαληθεύουμε τις μαθηματικές λύσεις μέσω της numPy:

In [ ]:
import numpy as np
np.random.seed(14)                    # seed = final 4 digits of AM
X = np.random.randint(0,10, (3,4))    # random numpy array of shape (3,4)
Y = np.random.randint(0,10, (4,3))    # random numpy array of shape (4,3)

a = np.random.randint(0,10,4)         #vector row (random numpy array of shape row)
b = np.random.randint(0,10,4)

print ("(Question 1.1)")
print("ab = ", end="")
print(np.inner(a,b))

print ("\n(Question 1.2)")
print("Xa = ", end="")
print(X.dot(a))

print ("\n(Question 1.3)")
print("XY =")
print(X.dot(Y))

print ("\n(Question 1.4)")
print("l2-norm of a = ||a||_2 = ", end="")
print(np.linalg.norm(a))

print ("\n(Question 1.5)")
print("frobenius norm of X = ||X||_F = ", end="")
print(np.linalg.norm(X))


# [Ερώτημα 2: Υπολογισμός παραγώγων]

# (2.1)
Συνάρτηση: $f(x) = x^TAx + b^Tx $

Η παράγωγος μιας συνάρτησης $f:R\rightarrow R^d, \nabla f(x)$, ως προς το διάνυσμα $x \in R^d$ είναι:
$\nabla f(x)=\begin{pmatrix} \frac{\partial f}{\partial  x_1}  \\ \vdots\\ \frac{\partial f}{\partial  x_d} \end{pmatrix} \in R^d$

Θεωρούμε ότι:

$g(x) = x^TAx$ και $h(x) = b^Tx$

$\partial f(x) = \partial g(x) + \partial h(x)$

Για την $g(x)$:

\begin{align}
y & = g(x) \\
& = x^TAx \\
& = \begin{pmatrix}x1  \\ \vdots\\ x_d\end{pmatrix} \begin{pmatrix} a_{11} & a_{12} & \dots & a_{1d}\\  \vdots & \vdots &\ddots & \vdots \\ a_{d1} & a_{d2} & \dots & a_{dd} \end{pmatrix} \begin{pmatrix}x1 \dots x_d\end{pmatrix}\\
& = \sum_{i=1}^d\sum_{j=1}^d a_{ij}x_ix_j \\
& = \sum_{i=1}^da_{i1}x_ix_1+\sum_{j=1}^da_{1j}x_1x_j+\sum_{i=2}^d\sum_{j=2}^d a_{ij}x_ix_j\\
\text{Άρα έχουμε:} \\
\frac{\partial g}{\partial  x_1} & = \sum_{i=1}^da_{i1}x_i+\sum_{j=1}^da_{1j}x_j \\
& = \sum_{i=1}^da_{1i}x_i+\sum_{i=1}^da_{1i}x_i \,[\text{αφού} \; a_{1i}=a_{1i}]\\
& = 2\sum_{i=1}^da_{1i}x_i \\ 
\frac{\partial g}{\partial  x} 
& = \begin{pmatrix} 2\sum_{i=1}^na_{1i}x_i \\ \vdots\\ 2 \sum_{i=1}^na_{ni}x_i \end{pmatrix} \\
& = 2\begin{pmatrix} a_{11} & a_{12} & \dots & a_{1d}\\  \vdots & \vdots &\ddots & \vdots \\ a_{d1} & a_{d2} & \dots & a_{dd} \end{pmatrix}
\begin{pmatrix}x_1  \\ \vdots \\ x_n \end{pmatrix}\\ 
& = 2Ax
\end{align}

Για την $h(x)$:

\begin{align}
y & = h(x) \\
& = b^Tx \\
& = \begin{pmatrix}b1  \\ \vdots\\ b_d\end{pmatrix}\begin{pmatrix}x1 \dots x_d\end{pmatrix}\\
& = \sum_{i=1}^d b_i x_i \\
& =  b_1 x_1 + \sum_{i=2}^d b_i x_i \\
\text{Άρα έχουμε:} \\
\frac{\partial h}{\partial  x_1} & = b1\\ 
\frac{\partial h}{\partial  x} 
& = \begin{pmatrix} b_1 \\ b_2\\ \vdots\\ b_d\end{pmatrix} \\
& = b^T
\end{align}

Συνολικά

Η παράγωγος της συνάρτησης $f$ ως προς το διάνυσμα $x$ είναι:

$\nabla f(x) = 2Ax + b^Τ $

# (2.2)

Για να βρούμε, αναλυτικά και σε κλειστή μορφή (closed form solution) το ολικό ελάχιστο του προβλήματος βελτιστοποίησης:

Θέτουμε:
$U = A-XB$ και $f = \|U\|_F^2$

Από matrix cookbook γνωρίζουμε ότι $\|U\|_F^2 = Tr[U \cdot U^T]$ οπότε:

\begin{align}
\|A-XB\|_F^2 &= Tr[(A-XB) \cdot (A-XB)^T]\\
\end{align}

Παραγωγίζουμε γνωρίζοντας από matrix cookbook ότι $\frac{\partial Tr(F(X))}{\partial X} = f(X)^T \\ $:

\begin{align}
\frac{\partial}{\partial X}Tr[(A-XB) \cdot (A-XB)^T] &= \frac{\partial}{\partial X}Tr[(A-XB) \cdot (A^T-X^TB^T)]\\
&= \frac{\partial}{\partial X}Tr[AA^T-AX^TB^T-XBA^T - XBX^TB^T]\\\\
&= (-A^ΤB - BA^T + 2X^TBB^T)^T \\
&= (-2B(A^T-X^TB^T))^T\\
&= -2B^T(A-XB)
\end{align}

Θέτουμε την παράγωγο ίση με 0 και λύνουμε ως προς $X$:

\begin{align}
-2B^T(A-XB) &= 0\\
2B^TXB &= 2B^TA\\
X &= \frac{A}{B}
\end{align}

Τελικά: 
\begin{align}
min \|A-XB\|_F^2 &= \|A-\frac{A}{B}B\|_F^2\\
&= 0
\end{align}

# [Ερώτημα 3: Gradient descent]

#Για τη συνάρτηση: $f_1([x_1, x_2]^T) = f_1(x_1, x_2) = (x_1 − 2)^2 + (x_2 − 3)^2$

Ο αλγόριθμος βρίσκει το global minimum της f σε δύο επαναλήψεις για learning rate = 0.5, ενώ για μικρότερα learning rates καταλήγει στο global minimum με επαναλήψεις που αυξάνονται όσο μικραίνει το learning rate. Παρακάτω δοκιμάζω τον αλγόριθμο για τη συνάρτηση με precision = 0.00001 για:

learning rate = 0.5, maxIter = 10 και 

learning rate = 0.2, maxIter = 20

και εμφανίζω γραφήματα που να απεικονίζουν την τιμή της συνάρτησης (κάθετος άξονας) ως συνάρτηση των επαναλήψεων (οριζόντιος άξονας).

In [ ]:
##############################################################################################################################

from sympy import *
import numpy as np
import matplotlib.pyplot as plt

x1 = Symbol('x1')
x2 = Symbol('x2')

f = (x1 - 2)**2 + (x2 - 3)**2

# First partial derivative with respect to x1
fx1 = f.diff(x1)
# fpx1 = 2*x1 - 4

# First partial derivative with respect to x2
fx2 = f.diff(x2)
# fpx2 = 2*x2 - 6

gradient = [fx1,fx2]
x = 0
y = 0
lrate = 0.5
numIter = 0     
maxIter = 10
precision = 0.001

T = []
F = []

while True:
  tempx = x - lrate * fx1.subs(x1,x).subs(x2,y).evalf()
  tempy = y - lrate * fx2.subs(x1,x).subs(x2,y).evalf()

  numIter += 1
  if numIter > maxIter:
    break

  #If the values of x1/x2 change less than the amount of precision, break
  if abs(tempx-x) < precision and abs(tempy-y) < precision:
    converge = True
    break

  x = tempx
  y = tempy
  print("Iteration",numIter)
  print("f value:",f.subs(x1,x).subs(x2,y).evalf())
  T.append(numIter)
  F.append(f.subs(x1,x).subs(x2,y).evalf())

if converge:
  print("\nNumber of iterations:",numIter)
  print("f converges to a minimum:", int(round(f.subs(x1,tempx).subs(x2,tempy).evalf())))
  print("x =",tempx,sep=" ")
  print("y =",tempy,sep=" ")

  T.append(numIter)
  F.append(f.subs(x1,x).subs(x2,y).evalf())
  plt.plot(T,F)
  plt.xlabel("Iterations (T)")
  plt.ylabel("Value of Function (F)")
  plt.title("Learning Rate = "+str(lrate))
  plt.show()

In [ ]:
##############################################################################################################################

from sympy import *
import numpy as np
import matplotlib.pyplot as plt

x1 = Symbol('x1')
x2 = Symbol('x2')

f = (x1 - 2)**2 + (x2 - 3)**2

# First partial derivative with respect to x1
fx1 = f.diff(x1)
# fpx1 = 2*x1 - 4

# First partial derivative with respect to x2
fx2 = f.diff(x2)
# fpx2 = 2*x2 - 6

gradient = [fx1,fx2]
x = 0
y = 0
lrate = 0.2
numIter = 0     
maxIter = 20
precision = 0.001

T = []
F = []

while True:
  tempx = x - lrate * fx1.subs(x1,x).subs(x2,y).evalf()
  tempy = y - lrate * fx2.subs(x1,x).subs(x2,y).evalf()

  numIter += 1
  if numIter > maxIter:
    break

  #If the values of x1/x2 change less than the amount of precision, break
  if abs(tempx-x) < precision and abs(tempy-y) < precision:
    converge = True
    break

  x = tempx
  y = tempy
  print("Iteration",numIter)
  print("f value:",f.subs(x1,x).subs(x2,y).evalf())
  T.append(numIter)
  F.append(f.subs(x1,x).subs(x2,y).evalf())

if converge:
  print("\nNumber of iterations:",numIter)
  print("f converges to a minimum:", int(round(f.subs(x1,tempx).subs(x2,tempy).evalf())))
  print("x =",tempx,sep=" ")
  print("y =",tempy,sep=" ")

  T.append(numIter)
  F.append(f.subs(x1,x).subs(x2,y).evalf())
  plt.plot(T,F)
  plt.xlabel("Iterations (T)")
  plt.ylabel("Value of Function (F)")
  plt.title("Learning Rate = "+str(lrate))
  plt.show()

#Για τη συνάρτηση: $f_2([x_1, x_2]^T) = f_2(x_1, x_2) = (1 − (x_2 − 3))^2 + 20 ((x_1 + 3) − (x_2 − 3)^2)^2$

Ο αλγόριθμος δεν βρίσκει το global minimum της f για τιμές του learning rate > 0.005. Αυτό συμβαίνει καθώς η συνάρτηση είναι "δύσκολη", επομένως με μεγάλα βήματα είναι πολύ εύκολο να κάνει ο αλγόριθμος λάθος και η τιμή της f να κάνει diverge αντί για converge. 

Βρήκα το "καλύτερο" αποτέλεσμα (ελάχιστες επαναλήψεις) για learning rate = 0.0042 όπου και καταλήγει σε global minimum σε 3254 επαναλήψεις (precision = 0.00001)

Παρακάτω δοκιμάζω τον αλγόριθμο για τη συνάρτηση με precision = 0.00001 για:

learning rate = 0.5, maxIter = 10 

learning rate = 0.0042, maxIter = 5000 

learning rate = 0.002, maxIter = 10000

και εμφανίζω γραφήματα που να απεικονίζουν την τιμή της συνάρτησης (κάθετος άξονας) ως συνάρτηση των επαναλήψεων (οριζόντιος άξονας). Για καλύτερα γραφήματα έχω βάλει σε σχόλιο το precision που αναδεικνύει καλύτερα το γράφημα για κάθε παράδειγμα (Προφανώς δεν καταλήγουμε σε τέλεια λύση για τα x1,x2,f) 

In [ ]:
##############################################################################################################################

from sympy import *
import matplotlib.pyplot as plt

x1 = Symbol('x1')
x2 = Symbol('x2')

f = (1-(x2-3))**2 + 20*((x1+3)-(x2-3)**2)**2

# First partial derivative with respect to x1
fx1 = f.diff(x1)
# fx1 = 40*x1 - 40*(x2 - 3)**2 + 120

# First partial derivative with respect to x2
fx2 = f.diff(x2)
# fx2 = 2*x2 + 20*(12 - 4*x2)*(x1 - (x2 - 3)**2 + 3) - 8


gradient = [fx1,fx2]
x = 0
y = 0
lrate = 0.5
numIter = 0
maxIter = 10
precision = 0.00001
converge = False

T = []
F = []

while True:
  tempx = x - lrate * fx1.subs(x1,x).subs(x2,y).evalf()
  tempy = y - lrate * fx2.subs(x1,x).subs(x2,y).evalf()

  numIter += 1
  if numIter > maxIter:
    break

  #If the values of x1/x2 change less than the amount of precision, break
  if abs(tempx-x) < precision and abs(tempy-y) < precision:
    converge = True
    break

  x = tempx
  y = tempy
  print("Iteration",numIter)
  print("f value:",f.subs(x1,x).subs(x2,y).evalf())
  T.append(numIter)
  F.append(f.subs(x1,x).subs(x2,y).evalf())

if converge:
  print("\nNumber of iterations:",numIter)
  print("f converges to a minimum:", int(round(f.subs(x1,tempx).subs(x2,tempy).evalf())))
  print("x =",tempx,sep=" ")
  print("y =",tempy,sep=" ")

  T.append(numIter)
  F.append(f.subs(x1,x).subs(x2,y).evalf())
  plt.plot(T,F)
  plt.xlabel("Iterations (T)")
  plt.ylabel("Value of Function (F)")
  plt.title("Learning Rate = "+str(lrate))
  plt.show()

In [ ]:
##############################################################################################################################

from sympy import *
import matplotlib.pyplot as plt

x1 = Symbol('x1')
x2 = Symbol('x2')

f = (1-(x2-3))**2 + 20*((x1+3)-(x2-3)**2)**2

# First partial derivative with respect to x1
fx1 = f.diff(x1)
# fx1 = 40*x1 - 40*(x2 - 3)**2 + 120

# First partial derivative with respect to x2
fx2 = f.diff(x2)
# fx2 = 2*x2 + 20*(12 - 4*x2)*(x1 - (x2 - 3)**2 + 3) - 8


gradient = [fx1,fx2]
x = 0
y = 0
lrate = 0.0042
numIter = 0
maxIter = 5000
precision = 0.00001                #0.01
converge = False

T = []
F = []
printCount = 0

while True:
  tempx = x - lrate * fx1.subs(x1,x).subs(x2,y).evalf()
  tempy = y - lrate * fx2.subs(x1,x).subs(x2,y).evalf()

  numIter += 1
  if numIter > maxIter:
    break

  #If the values of x1/x2 change less than the amount of precision, break
  if abs(tempx-x) < precision and abs(tempy-y) < precision:
    converge = True
    break

  x = tempx
  y = tempy
  printCount += 1
  if printCount == 300:
    print("Iteration",numIter)
    print("f value:",f.subs(x1,x).subs(x2,y).evalf())
    printCount = 0
  T.append(numIter)
  F.append(f.subs(x1,x).subs(x2,y).evalf())

if converge:
  print("\nNumber of iterations:",numIter)
  print("f converges to a minimum:", int(round(f.subs(x1,tempx).subs(x2,tempy).evalf())))
  print("x =",tempx,sep=" ")
  print("y =",tempy,sep=" ")

  T.append(numIter)
  F.append(f.subs(x1,x).subs(x2,y).evalf())
  plt.plot(T,F)
  plt.xlabel("Iterations (T)")
  plt.ylabel("Value of Function (F)")
  plt.title("Learning Rate = "+str(lrate))
  plt.show()


In [ ]:
##############################################################################################################################

from sympy import *
import matplotlib.pyplot as plt

x1 = Symbol('x1')
x2 = Symbol('x2')

f = (1-(x2-3))**2 + 20*((x1+3)-(x2-3)**2)**2

# First partial derivative with respect to x1
fx1 = f.diff(x1)

# First partial derivative with respect to x2
fx2 = f.diff(x2)

gradient = [fx1,fx2]
x = 0
y = 0
lrate = 0.002
numIter = 0
maxIter = 10000
precision = 0.00001            #0.004
converge = False

T = []
F = []
printCount = 0

while True:
  tempx = x - lrate * fx1.subs(x1,x).subs(x2,y).evalf()
  tempy = y - lrate * fx2.subs(x1,x).subs(x2,y).evalf()

  numIter += 1
  if numIter > maxIter:
    break

  #If the values of x1/x2 change less than the amount of precision, break
  if abs(tempx-x) < precision and abs(tempy-y) < precision:
    converge = True
    break

  x = tempx
  y = tempy
  printCount += 1
  if printCount == 300:
    print("Iteration",numIter)
    print("f value:",f.subs(x1,x).subs(x2,y).evalf())
    printCount = 0
  T.append(numIter)
  F.append(f.subs(x1,x).subs(x2,y).evalf())

if converge:
  print("Number of iterations:",numIter)
  print("f converges to a minimum:", int(round(f.subs(x1,tempx).subs(x2,tempy).evalf())))
  print("x =",tempx,sep=" ")
  print("y =",tempy,sep=" ")

  T.append(numIter)
  F.append(f.subs(x1,x).subs(x2,y).evalf())
  plt.plot(T,F)
  plt.xlabel("Iterations (T)")
  plt.ylabel("Value of Function (F)")
  plt.title("Learning Rate = "+str(lrate))
  plt.show()


# Συμπέρασμα:

Όπως φαίνεται από το παράδειγμα της πρώτης συνάρτησης και ιδιαίτερα στο παράδειγμα της δεύτερης συνάρτησης που είναι πιο "δύσκολη" για τον αλγόριθμο, η τιμή του learning rate είναι αντιστρόφως ανάλογη του αριθμού των επαναλήψεων, είναι όμως ανάλογη της πιθανότητας λάθους.

Επομένως, για κάθε συνάρτηση, ανάλογα με τη δυσκολία της είναι θεμιτό να βρίσκουμε learning rate το οποίο ελαχιστοποιεί τον αριθμό επαναλήψεων μέχρι να φτάσουμε στο global minimum της συνάρτησης με αρκετή ακρίβεια (precision), ΧΩΡΙΣ όμως αυτό το learning rate να συγκλίνει πρώιμα σε λάθος σημείο ή να προκαλεί απόκλιση (divergence) στη συνάρτηση μας. 